// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnmngPkTE6p7HonT-RcAROPzB79IiPXuE',
    appId: '1:405241642480:web:604320f723b8b9f976f135',
    messagingSenderId: '405241642480',
    projectId: 'glow-me-9ddd0',
    authDomain: 'glow-me-9ddd0.firebaseapp.com',
    storageBucket: 'glow-me-9ddd0.firebasestorage.app',
    measurementId: 'G-X5K3RSP8QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA19-9dR-gkpz0cebEBVVLuSzaeoex8sUo',
    appId: '1:405241642480:android:19beb293639546fa76f135',
    messagingSenderId: '405241642480',
    projectId: 'glow-me-9ddd0',
    storageBucket: 'glow-me-9ddd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhItHuaIM5J8zn2MuBPml65yqgb1w-z8E',
    appId: '1:405241642480:ios:020578fee195bc1c76f135',
    messagingSenderId: '405241642480',
    projectId: 'glow-me-9ddd0',
    storageBucket: 'glow-me-9ddd0.firebasestorage.app',
    iosBundleId: 'com.example.glowMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhItHuaIM5J8zn2MuBPml65yqgb1w-z8E',
    appId: '1:405241642480:ios:020578fee195bc1c76f135',
    messagingSenderId: '405241642480',
    projectId: 'glow-me-9ddd0',
    storageBucket: 'glow-me-9ddd0.firebasestorage.app',
    iosBundleId: 'com.example.glowMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnmngPkTE6p7HonT-RcAROPzB79IiPXuE',
    appId: '1:405241642480:web:6f788dee7dee5e4076f135',
    messagingSenderId: '405241642480',
    projectId: 'glow-me-9ddd0',
    authDomain: 'glow-me-9ddd0.firebaseapp.com',
    storageBucket: 'glow-me-9ddd0.firebasestorage.app',
    measurementId: 'G-DXWY91P3N6',
  );
}
